# Generated by Django 4.1.7 on 2023-05-04 16:36

import beauty_salon_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon_app', '0003_alter_client_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[beauty_salon_app.models.positive_int], verbose_name='price'),
        ),
    ]
