# Generated by Django 4.1.7 on 2023-05-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon_app', '0004_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='duration'),
            preserve_default=False,
        ),
    ]
