# Generated by Django 4.1.7 on 2023-05-05 19:33

import beauty_salon_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon_app', '0005_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=40, validators=[beauty_salon_app.models.check_phone], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=40, validators=[beauty_salon_app.models.check_phone], verbose_name='phone'),
        ),
    ]
