# Generated by Django 4.1.7 on 2023-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon_app', '0006_alter_client_phone_alter_doctor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='photo'),
        ),
    ]
