# Generated by Django 4.1.7 on 2023-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon_app', '0007_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='photo'),
        ),
    ]
