# Generated by Django 4.1.7 on 2023-06-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon_app', '0008_service_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status_payment',
            field=models.CharField(choices=[('NP', 'Не оплачено'), ('P', 'Оплачено')], default='NP', max_length=20, verbose_name='status payment'),
        ),
    ]
